apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
      replace: true      
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision:  2.x
    helm:
      releaseName: loki-stack
      values: |
        grafana:
          enabled: false
          sidecar:
            datasources:
              enabled: true
              maxLines: 1000
        promtail:
          enabled: true
        loki:
          enabled: true
          isDefault: false
          serviceMonitor:
            enabled: true
            additionalLabels:
              app.kubernetes.io/part-of: kube-prometheus-stack
          config:
            chunk_store_config:
              max_look_back_period: 0s
            table_manager:
              retention_deletes_enabled: true
              retention_period: 12h
